# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Maris Botero
email: maris2143@gmail.com
description: ⭐🌟 print("My name is Maris and I like to play with code =)") 💚 May humanity be our only race, and love our religion💛
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: marisbotero
github_username:  marisbotero

paginate: 2
locale: en_us
nav_list:
  Home : ['Home', '/', 'fa-home']
  About : ['About', '/about', 'fa-heart']
  Motivation : ['Art', '/category/art/', 'fa-star']
  Front End : ['Robots', '/category/Robots', 'fa-code']
  Back End : ['Code', '/category/Code/', 'fa-diamond']

single_footer: '<p> Made with <i class="fa fa-heart"></i> | Hosted by Github. | 2018 © </p>'

markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-mentions
include: ["_pages"]
exclude:
  - Gemfile
  - Gemfile.lock

jekyll-mentions: https://twitter.com

livereload: true

sass:
  style: compressed

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      comments: true
      feature_image: recommend-omniauth
      author_name: "Maris Botero"
      read_time: 3
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages" # previously `post` in Jekyll 2.2.
    values:
      layout: "page"
